name: stream_feed_example
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  stream_feed:
    path: ../packages/stream_feed
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
