name: stream_feed_flutter
description: Stream Feed official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.0.0
homepage: https://getstream.io/
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  animations: ^2.0.0
  chewie: ^1.2.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  image_picker: ^0.8.4+4
  rxdart: ^0.27.1
  path_provider: ^2.0.5
  photo_view: ^0.12.0
  stream_feed_flutter_core:
    path: ../stream_feed_flutter_core
  timeago: ^3.0.2
  url_launcher: ^6.0.6
  video_thumbnail: ^0.4.3

dev_dependencies:
  golden_toolkit: ^0.9.0
  nested: ^1.0.0
  mocktail_image_network: ^0.1.0
  test: ^1.14.4

flutter:
  assets:
    - lib/svgs/