name: stream_feed_flutter
description: Stream Feed official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.0.0
homepage: https://getstream.io/
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter
  timeago: ^3.0.2
  equatable: ^2.0.2
  url_launcher: ^6.0.6
  animations: ^2.0.0
  image_picker: ^0.8.2
  stream_feed_flutter_core:
    path: ../stream_feed_flutter_core

dev_dependencies:
  golden_toolkit: ^0.9.0
  pedantic: ^1.9.0
  test: ^1.14.4
  mocktail_image_network: ^0.1.0

flutter:
  assets:
    - lib/svgs/