name: stream_feed_flutter
description: Stream Feed official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.0.0
homepage: https://getstream.io/
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  chewie: ^1.3.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  image_picker: ^0.8.4+4
  path_provider: ^2.0.5
  photo_view: ^0.14.0
  rxdart: ^0.27.1
  stream_feed_flutter_core: ^0.8.0
  timeago: ^3.0.2
  url_launcher: ^6.0.6
  video_thumbnail: ^0.5.0

dependency_overrides:
  stream_feed_flutter_core:
    path: ../stream_feed_flutter_core

dev_dependencies:
  golden_toolkit: ^0.13.0
  mocktail_image_network: ^0.3.1
  nested: ^1.0.0
  test: ^1.14.4

flutter:
  assets:
    - lib/svgs/
