name: pana

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  faye_dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/faye_dart
      - name: Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          MINIMUM: 110
        run: |
          if (( TOTAL < MINIMUM ))
          then
            echo "Score regressed: $TOTAL is below $MINIMUM"
            exit 1
          fi

  stream_feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/stream_feed
      - name: Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          MINIMUM: 120
        run: |
          if (( TOTAL < MINIMUM ))
          then
            echo "Score regressed: $TOTAL is below $MINIMUM"
            exit 1
          fi
  stream_feed_flutter_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/stream_feed_flutter_core
      - name: Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          MINIMUM: 130
        run: |
          if (( TOTAL < MINIMUM ))
          then
            echo "Score regressed: $TOTAL is below $MINIMUM"
            exit 1
          fi
